version: "3"

services:
  # Angular Frontend
  angular:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - nodejs
      - chatbot
    environment:
      - HOST=0.0.0.0
  # Flask Chatbot

  chatbot:
    build:
      context: ./chatbot
    environment:
      - FLASK_APP=chat.py
    ports:
      - "5001:5001"
    command: flask run --host=0.0.0.0 --port=5001
    depends_on:
      - nodejs

  # Node.js Backend
  nodejs:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456o
      - MYSQL_DATABASE=health_connect
      - MYSQL_PORT=3306
      - EMAIL_USER=rais.asma99@gmail.com
      - APP_PASSWORD=jznlipcscovlaspt
      - PORT=5000
      - JWT_SECRET=09b2c5bb...
      - JWT_EXPIRES_IN=1d
      - GOOGLE_CLIENT_ID=34200...
      - GOOGLE_CLIENT_SECRET=GOCSPX...
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456o
      - MYSQL_DATABASE=health_connect
    volumes:
      - mysql_data:/var/lib/mysql

 

volumes:
  mysql_data:
