version: "3"

services:
  # Angular Frontend
  angular:
    build:
      context: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - nodejs
    # Ensure Angular listens on all network interfaces inside the container
    environment:
      - HOST=0.0.0.0
  
  # Node.js Backend
  nodejs:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456o
      - MYSQL_DATABASE=health_connect
      - MYSQL_PORT=3306
      - EMAIL_USER=rais.asma99@gmail.com
      - APP_PASSWORD=jznlipcscovlaspt
      - PORT=5000
      - JWT_SECRET=09b2c5bbec5cf8c62e8380d466838ab12cc1e81e36ed100fb3db9a53f446551ce4ed42d8f6f79112d0b4ebfc124e3865b7f1bb9d150a49e2782f8f79eddf4be2bf88cecd0fa41a4b07310bba531002b63c0aa873d7cb97a83e4870aaf26b852bd6dc980c4913b42eed219e9b4ce683c440b9ee02a933e3a1954b89520ddddf6b9475b59c5eed97e9afa2df14e2f6dcbfd9a96d7b469b085871b5f04647a73a02b1717a1209275cfc1e07d33f6185c7669d664da89a81298a051564ade9547aef88e4f86a3e3c1cf5dbbf95736669fa6a91ea214e0f1f594c96da2b1067dd834ca1ce6f5f6d5bf7e69f123bc1d1d147bd9c5ab90142b88a7bec202dc2149755d5
      - JWT_EXPIRES_IN=1d
      - GOOGLE_CLIENT_ID=34200255311-t3hle21ub407mqb46nqn1hbdv7jmtb0k.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=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
    depends_on:
      - mysql

  # MySQL Database
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=123456o
      - MYSQL_DATABASE=health_connect
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
